[package]
name = "metamsg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/connection",
    "crates/discovery",
    "crates/network_device_link",
    "crates/authmanager",
    "crates/transmission",
    "crates/adapter",
    "crates/metamsg-mqtt",
]

[workspace.dependencies]
thiserror = "1.0.48"
